Revert "Always try and enable the new_uninit feature."
This reverts commit d678fbfb4802deac0258a9a53eac960d6e6e1bc5.

The original change broke Chromium:

```
error[E0725]: the feature `new_uninit` is not in the list of allowed features
  --> ../../third_party/boringssl/src/rust/bssl-crypto/src/lib.rs:28:12
   |
28 | #![feature(new_uninit)]
   |            ^^^^^^^^^^
```

(cherry picked from commit a66e808c0f15a42b6e9b5b5c42cc02d458835da1)
Change-Id: If989e4c6d569bce924982ea6c682be174857a603
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/75047
Reviewed-by: David Benjamin <davidben@google.com>
Commit-Queue: David Benjamin <davidben@google.com>
Auto-Submit: Adam Langley <agl@google.com>
Commit-Queue: Adam Langley <agl@google.com>